/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    tags: Tag;
    teams: Team;
    players: Player;
    gallery: Gallery;
    board: Board;
    staff: Staff;
    sponsors: Sponsor;
    heroSlides: HeroSlide;
    staticPages: StaticPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    board: BoardSelect<false> | BoardSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    heroSlides: HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    staticPages: StaticPagesSelect<false> | StaticPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteConfig: SiteConfig;
    season: Season;
  };
  globalsSelect: {
    siteConfig: SiteConfigSelect<false> | SiteConfigSelect<true>;
    season: SeasonSelect<false> | SeasonSelect<true>;
  };
  locale: null;
  widgets: {
    'season-sync': SeasonSyncWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'redaktor' | 'trener';
  /**
   * Używane tylko dla roli trener — ogranicza edycję zawodników do tej drużyny.
   */
  team?: (number | null) | Team;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Drużyny widoczne na /druzyny. Skład (kadra) jest w osobnej kolekcji Players.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Część adresu po /druzyny/. Wypełniane auto z nazwy, można nadpisać.
   */
  slug: string;
  category: 'seniorzy' | 'rezerwy' | 'juniorzy' | 'trampkarze' | 'orlik' | 'zak' | 'skrzat' | 'kobiety' | 'inna';
  league?: string | null;
  coach: string;
  assistantCoach?: string | null;
  trainingSchedule?: string | null;
  /**
   * Opcjonalnie. Jeśli brak, strona pokaże układ bez zdjęcia.
   */
  photo?: (number | null) | Media;
  /**
   * Wyższa wartość = wyżej na listach.
   */
  order?: number | null;
  /**
   * Treść renderowana na stronie drużyny. Dla spójności używamy Lexical (jak w newsach).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Krótki opis obrazka (np. „Herb WKS Wierzbice"). Może być nadpisany na poziomie newsa polem „Cover ALT".
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Wpisy widoczne na /aktualnosci. Pole "Szkic" ukrywa news przed publikacją.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Część adresu po /aktualnosci/. Wypełniane auto z tytułu, można nadpisać.
   */
  slug?: string | null;
  date: string;
  /**
   * Zaznacz żeby ukryć przed publikacją na stronie.
   */
  draft?: boolean | null;
  /**
   * Wybierz istniejące tagi lub dodaj nowy ("Create new").
   */
  tags?: (number | Tag)[] | null;
  author?: string | null;
  /**
   * Krótki opis widoczny na liście newsów (max 2-3 zdania).
   */
  excerpt: string;
  /**
   * Wgraj plik (JPEG/PNG/WebP/GIF). Serwis automatycznie wygeneruje warianty thumbnail / card / hero w WebP.
   */
  cover?: (number | null) | Media;
  /**
   * Opcjonalnie nadpisuje `alt` z pliku Media w kontekście tego newsa. Jeśli puste — używamy `alt` z Media.
   */
  coverAlt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcjonalnie. Pełny URL do posta na fanpage (https://www.facebook.com/...).
   */
  facebookUrl?: string | null;
  /**
   * Zaznacz jeśli treść z Facebooka została skrócona (na froncie pokażemy "Czytaj całość na FB").
   */
  truncated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tagi pomagają grupować newsy (np. wszystkie newsy o seniorach albo wszystkie o turniejach).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Wypełniane automatycznie z pola "Nazwa". Można nadpisać ręcznie (np. dla SEO).
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kadra drużyn. Każdy zawodnik należy do jednej drużyny (relacja do Teams).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  number?: number | null;
  /**
   * Np. "Bramkarz", "Obrońca", "Pomocnik", "Napastnik". Front grupuje zawodników po słowach-kluczach.
   */
  position?: string | null;
  team: number | Team;
  /**
   * Opcjonalny portret. Jeśli brak, karta pokaże watermark z herbem.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zdjęcia na /galeria. Kolejność = pole „Kolejność” (niższe = wcześniej).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  alt: string;
  caption?: string | null;
  /**
   * Sort rosnąco: 0, 1, 2…
   */
  order?: number | null;
  category?: string | null;
  /**
   * Rezerwa pod przyszłe albumy — na razie puste.
   */
  albumId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zarząd klubu (sekcja /o-klubie).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board".
 */
export interface Board {
  id: number;
  name: string;
  role: string;
  highlight?: boolean | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sztab szkoleniowy (sekcja /o-klubie).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: string;
  type: 'trener_pierwszej_druzyny' | 'trener_mlodziezy' | 'inne';
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsorzy i partnerzy klubu (strona /sponsorzy + komponenty).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  tier: 'strategiczny' | 'glowny' | 'wspierajacy';
  logo: number | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Karuzela na stronie głównej.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroSlides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Treści stron: o-klubie / nabory / kontakt / polityka-prywatnosci.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticPages".
 */
export interface StaticPage {
  id: number;
  slug: 'o-klubie' | 'nabory' | 'kontakt' | 'polityka-prywatnosci';
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'board';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'heroSlides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'staticPages';
        value: number | StaticPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  team?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  draft?: T;
  tags?: T;
  author?: T;
  excerpt?: T;
  cover?: T;
  coverAlt?: T;
  body?: T;
  facebookUrl?: T;
  truncated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  league?: T;
  coach?: T;
  assistantCoach?: T;
  trainingSchedule?: T;
  photo?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  position?: T;
  team?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  caption?: T;
  order?: T;
  category?: T;
  albumId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board_select".
 */
export interface BoardSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  highlight?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  type?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroSlides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  kicker?: T;
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticPages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ustawienia globalne strony (nawigacja, kontakt, social). Front ma fallback do `site.ts` gdy CMS OFF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig".
 */
export interface SiteConfig {
  id: number;
  site: {
    name: string;
    shortName: string;
    tagline?: string | null;
    description?: string | null;
    url?: string | null;
    language?: string | null;
    founded?: number | null;
    reactivated?: number | null;
    league?: string | null;
    city?: string | null;
    region?: string | null;
    defaultOgImage?: string | null;
  };
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
    };
    officeAddress?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
    };
    googleMapsEmbedSrc?: string | null;
    googleMapsLink?: string | null;
  };
  social?: {
    facebook?: string | null;
    facebookAlt?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    facebookFollowers?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Snapshot tabeli i terminarza z 90minut.pl. Uzupełniane przez endpoint /api/season/sync (dashboard button + cron).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season".
 */
export interface Season {
  id: number;
  lastSync?: string | null;
  lastSyncStatus: 'idle' | 'running' | 'success' | 'error';
  lastSyncError?: string | null;
  /**
   * To jest “źródło prawdy” dla /terminarz w Astro. Front ma fallback do lokalnego season.json jeśli CMS niedostępny.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  site?:
    | T
    | {
        name?: T;
        shortName?: T;
        tagline?: T;
        description?: T;
        url?: T;
        language?: T;
        founded?: T;
        reactivated?: T;
        league?: T;
        city?: T;
        region?: T;
        defaultOgImage?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
              country?: T;
            };
        officeAddress?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
            };
        googleMapsEmbedSrc?: T;
        googleMapsLink?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        facebookAlt?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        facebookFollowers?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season_select".
 */
export interface SeasonSelect<T extends boolean = true> {
  lastSync?: T;
  lastSyncStatus?: T;
  lastSyncError?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season-sync_widget".
 */
export interface SeasonSyncWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}