/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    tags: Tag;
    teams: Team;
    players: Player;
    matches: Match;
    liveArchives: LiveArchive;
    'gallery-albums': GalleryAlbum;
    gallery: Gallery;
    board: Board;
    staff: Staff;
    sponsors: Sponsor;
    heroSlides: HeroSlide;
    staticPages: StaticPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    liveArchives: LiveArchivesSelect<false> | LiveArchivesSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    board: BoardSelect<false> | BoardSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    heroSlides: HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    staticPages: StaticPagesSelect<false> | StaticPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteConfig: SiteConfig;
    season: Season;
    liveMatch: LiveMatch;
  };
  globalsSelect: {
    siteConfig: SiteConfigSelect<false> | SiteConfigSelect<true>;
    season: SeasonSelect<false> | SeasonSelect<true>;
    liveMatch: LiveMatchSelect<false> | LiveMatchSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'redaktor' | 'trener';
  /**
   * Używane tylko dla roli trener — ogranicza edycję zawodników do tej drużyny.
   */
  team?: (number | null) | Team;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Drużyny widoczne na /druzyny. Skład (kadra) jest w osobnej kolekcji Players.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Część adresu po /druzyny/. Wypełniane auto z nazwy, można nadpisać.
   */
  slug: string;
  category: 'seniorzy' | 'rezerwy' | 'juniorzy' | 'trampkarze' | 'orlik' | 'zak' | 'skrzat' | 'kobiety' | 'inna';
  league?: string | null;
  coach: string;
  assistantCoach?: string | null;
  trainingSchedule?: string | null;
  /**
   * Opcjonalnie. Jeśli brak, strona pokaże układ bez zdjęcia.
   */
  photo?: (number | null) | Media;
  /**
   * Wyższa wartość = wyżej na listach.
   */
  order?: number | null;
  /**
   * Treść renderowana na stronie drużyny. Dla spójności używamy Lexical (jak w newsach).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Krótki opis obrazka (np. „Herb WKS Wierzbice"). Może być nadpisany na poziomie newsa polem „Cover ALT".
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Wpisy widoczne na /aktualnosci. Pole "Szkic" ukrywa news przed publikacją.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Część adresu po /aktualnosci/. Wypełniane auto z tytułu, można nadpisać.
   */
  slug?: string | null;
  date: string;
  /**
   * Zaznacz żeby ukryć przed publikacją na stronie.
   */
  draft?: boolean | null;
  /**
   * Wybierz istniejące tagi lub dodaj nowy ("Create new").
   */
  tags?: (number | Tag)[] | null;
  author?: string | null;
  /**
   * Krótki opis widoczny na liście newsów (max 2-3 zdania).
   */
  excerpt: string;
  /**
   * Wgraj plik (JPEG/PNG/WebP/GIF). Serwis automatycznie wygeneruje warianty thumbnail / card / hero w WebP.
   */
  cover?: (number | null) | Media;
  /**
   * Opcjonalnie nadpisuje `alt` z pliku Media w kontekście tego newsa. Jeśli puste — używamy `alt` z Media.
   */
  coverAlt?: string | null;
  /**
   * Opcjonalne „okienka” nakładane na zdjęcie okładkowe (np. „Zawodnik meczu”, „Z Facebooka”). Maks. 3 sztuki.
   */
  coverBadges?:
    | {
        label: string;
        variant: 'red' | 'blue' | 'green' | 'slate';
        /**
         * Jeśli ustawisz, okienko będzie klikalne (np. do Facebooka).
         */
        href?: string | null;
        newTab?: boolean | null;
        icon?: ('none' | 'facebook' | 'star' | 'trophy') | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcjonalnie. Pełny URL do posta na fanpage (https://www.facebook.com/...).
   */
  facebookUrl?: string | null;
  /**
   * Zaznacz jeśli treść z Facebooka została skrócona (na froncie pokażemy "Czytaj całość na FB").
   */
  truncated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tagi pomagają grupować newsy (np. wszystkie newsy o seniorach albo wszystkie o turniejach).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Wypełniane automatycznie z pola "Nazwa". Można nadpisać ręcznie (np. dla SEO).
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kadra drużyn. Każdy zawodnik należy do jednej drużyny (relacja do Teams).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  name: string;
  number?: number | null;
  /**
   * Np. "Bramkarz", "Obrońca", "Pomocnik", "Napastnik". Front grupuje zawodników po słowach-kluczach.
   */
  position?: string | null;
  team: number | Team;
  /**
   * Opcjonalny portret. Jeśli brak, karta pokaże watermark z herbem.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Terminarz w CMS (liga / sparing / puchar). Źródło propozycji dla relacji live oraz docelowo dla stron terminarza.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  competitionType: 'league' | 'friendly' | 'cup';
  /**
   * Np. „Klasa okręgowa · K24”, „Puchar Polski”.
   */
  competitionLabel?: string | null;
  kickoffPlanned: string;
  /**
   * Jeśli mecz zaczął się później, ustaw realny start — relacja live może liczyć minuty względem tej wartości.
   */
  kickoffReal?: string | null;
  venue: 'home' | 'away' | 'neutral';
  /**
   * Np. „Wierzbice”, „Stadion XYZ”.
   */
  locationLabel?: string | null;
  homeTeamLabel: string;
  awayTeamLabel: string;
  wksSide: 'home' | 'away';
  /**
   * Jeśli ustawione, relacja live może filtrować zawodników po tej drużynie.
   */
  wksTeam?: (number | null) | Team;
  /**
   * Wybierz kadrę na mecz. Lista jest pogrupowana po pozycjach dla szybkiej weryfikacji. Ustaw „Drużyna WKS”, żeby zawęzić listę, a potem użyj przycisku „Uzupełnij z drużyny WKS”, jeśli chcesz szybko zaznaczyć całą kadrę.
   */
  lineup?: (number | Player)[] | null;
  /**
   * Pomocniczy tytuł w liście meczów (generowany).
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Snapshoty zakończonych relacji live (status=ft). Służą do późniejszego napisania artykułu w aktualnościach. Wyniki w terminarzu uzupełniaj osobno.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liveArchives".
 */
export interface LiveArchive {
  id: number;
  /**
   * Auto: „Gospodarz vs Gość · DD miesiąc YYYY”.
   */
  title: string;
  finishedAt: string;
  match?: (number | null) | Match;
  kind?: ('league' | 'friendly' | 'cup' | 'custom') | null;
  competitionLabel?: string | null;
  homeLabel: string;
  awayLabel: string;
  scoreHome: number;
  scoreAway: number;
  /**
   * Auto: „X:Y”. Wygodne do listy.
   */
  finalScore?: string | null;
  wksSide?: ('home' | 'away') | null;
  /**
   * Pełna lista zdarzeń z relacji w momencie zakończenia (gole, kartki, asysty, minuty). Format JSON — używaj do napisania artykułu.
   */
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Skopiowana z meczu w terminarzu.
   */
  lineup?: (number | Player)[] | null;
  durationMinutes?: number | null;
  /**
   * Zaznacz po napisaniu relacji w sekcji Aktualności, żeby wiedzieć co jest „do zrobienia”.
   */
  usedForArticle?: boolean | null;
  /**
   * Pomocnicze notatki dla osoby piszącej relację.
   */
  articleNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wydarzenia / foldery na stronie Galeria. Do albumu przypisz zdjęcia w kolekcji „Galeria”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  title: string;
  /**
   * Adres: /galeria/[slug]. Puste = z tytułu. Nie używaj slug „bez-albumu” (zarezerwowany).
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Do sortowania albumów na liście (najnowsze pierwsze).
   */
  eventDate?: string | null;
  /**
   * Miniatura na karcie albumu. Bez okładki — pierwsze zdjęcie z albumu.
   */
  cover?: (number | null) | Media;
  /**
   * Niższe = wyżej (przy tej samej dacie).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zdjęcia w albumach: wybierz album lub zostaw puste — wtedy trafią do „Pozostałe” na /galeria.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  alt: string;
  caption?: string | null;
  /**
   * Sort rosnąco: 0, 1, 2…
   */
  order?: number | null;
  /**
   * Puste = sekcja „Pozostałe zdjęcia” na stronie galerii.
   */
  album?: (number | null) | GalleryAlbum;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Zarząd klubu (sekcja /o-klubie).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board".
 */
export interface Board {
  id: number;
  name: string;
  role: string;
  highlight?: boolean | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sztab szkoleniowy (sekcja /o-klubie).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: string;
  type: 'trener_pierwszej_druzyny' | 'trener_mlodziezy' | 'inne';
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sponsorzy i partnerzy klubu (strona /sponsorzy + komponenty).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  tier: 'strategiczny' | 'glowny' | 'wspierajacy';
  logo: number | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Karuzela na stronie głównej.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroSlides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  kicker?: string | null;
  title: string;
  subtitle?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Treści stron: o-klubie / nabory / kontakt / polityka-prywatnosci.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticPages".
 */
export interface StaticPage {
  id: number;
  slug: 'o-klubie' | 'nabory' | 'kontakt' | 'polityka-prywatnosci';
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'teams';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'liveArchives';
        value: number | LiveArchive;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'board';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'heroSlides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'staticPages';
        value: number | StaticPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  team?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  draft?: T;
  tags?: T;
  author?: T;
  excerpt?: T;
  cover?: T;
  coverAlt?: T;
  coverBadges?:
    | T
    | {
        label?: T;
        variant?: T;
        href?: T;
        newTab?: T;
        icon?: T;
        id?: T;
      };
  body?: T;
  facebookUrl?: T;
  truncated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  league?: T;
  coach?: T;
  assistantCoach?: T;
  trainingSchedule?: T;
  photo?: T;
  order?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  position?: T;
  team?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  competitionType?: T;
  competitionLabel?: T;
  kickoffPlanned?: T;
  kickoffReal?: T;
  venue?: T;
  locationLabel?: T;
  homeTeamLabel?: T;
  awayTeamLabel?: T;
  wksSide?: T;
  wksTeam?: T;
  lineup?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liveArchives_select".
 */
export interface LiveArchivesSelect<T extends boolean = true> {
  title?: T;
  finishedAt?: T;
  match?: T;
  kind?: T;
  competitionLabel?: T;
  homeLabel?: T;
  awayLabel?: T;
  scoreHome?: T;
  scoreAway?: T;
  finalScore?: T;
  wksSide?: T;
  events?: T;
  lineup?: T;
  durationMinutes?: T;
  usedForArticle?: T;
  articleNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventDate?: T;
  cover?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  caption?: T;
  order?: T;
  album?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board_select".
 */
export interface BoardSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  highlight?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  type?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroSlides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  kicker?: T;
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staticPages_select".
 */
export interface StaticPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ustawienia globalne strony (nawigacja, kontakt, social). Front ma fallback do `site.ts` gdy CMS OFF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig".
 */
export interface SiteConfig {
  id: number;
  site: {
    name: string;
    shortName: string;
    tagline?: string | null;
    description?: string | null;
    url?: string | null;
    language?: string | null;
    founded?: number | null;
    reactivated?: number | null;
    league?: string | null;
    city?: string | null;
    region?: string | null;
    defaultOgImage?: string | null;
  };
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
    };
    officeAddress?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
    };
    googleMapsEmbedSrc?: string | null;
    googleMapsLink?: string | null;
  };
  social?: {
    facebook?: string | null;
    facebookAlt?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    facebookFollowers?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Snapshot tabeli i terminarza z 90minut.pl. Uzupełniane przez endpoint /api/season/sync (przycisk poniżej + widget na dashboardzie + cron).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season".
 */
export interface Season {
  id: number;
  lastSync?: string | null;
  lastSyncStatus: 'idle' | 'running' | 'success' | 'error';
  lastSyncError?: string | null;
  /**
   * To jest “źródło prawdy” dla /terminarz w Astro. Front ma fallback do lokalnego season.json jeśli CMS niedostępny.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Relacja na żywo w hero na stronie głównej. Edycja przez „Utwórz mecz live” + Studio Live. Bezpośrednia edycja tutaj jest schowana, żeby nie mylić.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liveMatch".
 */
export interface LiveMatch {
  id: number;
  enabled?: boolean | null;
  status: 'pre' | 'live' | 'ht' | 'live2' | 'ft';
  mode: 'fromMatch' | 'manual';
  /**
   * Wpływa na sugestię meczu oraz etykietę rozgrywek.
   */
  kind: 'league' | 'friendly' | 'cup' | 'custom';
  /**
   * Wybierz mecz z terminarza (liga/sparing/puchar). Studio i widget mogą sugerować najbliższy.
   */
  match?: (number | null) | Match;
  /**
   * Np. „Sparing · Trening”, „Puchar Polski”, „Turniej”.
   */
  competitionCustomLabel?: string | null;
  /**
   * Np. „Klasa okręgowa · K24”, „Puchar Polski”, „Sparing”.
   */
  competitionLabel?: string | null;
  /**
   * Używane w zapowiedzi pre‑match na stronie głównej („Relacja na żywo od HH:MM”). Gdy tryb = terminarz, możesz zostawić puste.
   */
  kickoffPlanned?: string | null;
  /**
   * Od tego czasu liczona jest minuta w relacji (auto-clock).
   */
  kickoffReal?: string | null;
  addedTime1?: number | null;
  addedTime2?: number | null;
  /**
   * Ustawiane przez widget przy przejściu do przerwy.
   */
  pauseAt?: string | null;
  /**
   * Ustawiane przez widget przy starcie 2. połowy.
   */
  resumeAt?: string | null;
  homeLabel?: string | null;
  awayLabel?: string | null;
  manualCompetitionLabel?: string | null;
  manualHomeLabel?: string | null;
  manualAwayLabel?: string | null;
  scoreHome?: number | null;
  scoreAway?: number | null;
  /**
   * Najpierw najnowsze. Dla WKS wybieraj zawodników z listy (bez literówek), dla rywala wpisz tekst ręcznie.
   */
  events?:
    | {
        minute?: number | null;
        half?: ('1' | '2') | null;
        type: 'goal' | 'card' | 'sub' | 'info';
        team?: ('wks' | 'opponent') | null;
        ownGoal?: boolean | null;
        scorerWks?: (number | null) | Player;
        assistWks?: (number | null) | Player;
        /**
         * Użyj, jeśli strzelec nie jest na liście kadry.
         */
        scorerText?: string | null;
        /**
         * Opcjonalnie, jeśli nie wybierasz zawodnika.
         */
        assistText?: string | null;
        scorerOpponentText?: string | null;
        assistOpponentText?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteConfig_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  site?:
    | T
    | {
        name?: T;
        shortName?: T;
        tagline?: T;
        description?: T;
        url?: T;
        language?: T;
        founded?: T;
        reactivated?: T;
        league?: T;
        city?: T;
        region?: T;
        defaultOgImage?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
              country?: T;
            };
        officeAddress?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
            };
        googleMapsEmbedSrc?: T;
        googleMapsLink?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        facebookAlt?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        facebookFollowers?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "season_select".
 */
export interface SeasonSelect<T extends boolean = true> {
  lastSync?: T;
  lastSyncStatus?: T;
  lastSyncError?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liveMatch_select".
 */
export interface LiveMatchSelect<T extends boolean = true> {
  enabled?: T;
  status?: T;
  mode?: T;
  kind?: T;
  match?: T;
  competitionCustomLabel?: T;
  competitionLabel?: T;
  kickoffPlanned?: T;
  kickoffReal?: T;
  addedTime1?: T;
  addedTime2?: T;
  pauseAt?: T;
  resumeAt?: T;
  homeLabel?: T;
  awayLabel?: T;
  manualCompetitionLabel?: T;
  manualHomeLabel?: T;
  manualAwayLabel?: T;
  scoreHome?: T;
  scoreAway?: T;
  events?:
    | T
    | {
        minute?: T;
        half?: T;
        type?: T;
        team?: T;
        ownGoal?: T;
        scorerWks?: T;
        assistWks?: T;
        scorerText?: T;
        assistText?: T;
        scorerOpponentText?: T;
        assistOpponentText?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}